api:
  id: "resource::5dbdd855-7a22-4e25-8a74-845d1cb84b81:sapi-salesforce:1.0.0:raml:zip:sapi-salesforce.raml"
  instanceid: "20835379"
  
category:
  infoLog: "com.myorg.sapi.salesforce.logging.nonsensitive"
  debugLog: "com.myorg.sapi.salesforce.logging.sensitive"
