salesforce:
  client_id: "![k1kp2wqR0zdeMz9jgC0mTpaW1G3V5PjIuv3zwbiT7d9CbAczjZtati6V4a+z0rA4ruHqf339jd8ohZv+pMME0a9ee8/ag7KwuZZRM4m6bdFOBg65pQjZjw==]"
  client_secret: "![7ReKnl7xwk+Ri/0t8XWEiWkPU6qv5D6apIKiHMofSlD2qMn/znbQZC7B3lpp/+wKMCAyM06l2AsjK0SErman4URzQY9N4jIQ]"
  token_url: "![I4Fm94Iwpsx0bGqKVbXWoEEQoAPbS8avRwDn7To7ysOy/FenAJpNXjVkfjMau0pXtjwCiMgToEFiHQ36iUFCvO8/rPmiucsxTinU+L3N3rqSlpMAvHKNtQ==]"
  
http:
  host: "localhost"
  port: "8081"
  readTimeout: "30000"
  connectTimeout: "30000"